language: cpp
compiler:
    - gcc
sudo: true

# add Mrinal's cmake ppa
before_install:
    - yes | sudo add-apt-repository ppa:kalakris/cmake
    - sudo apt-get update -qq
install:
    - sudo apt-get update -qq
    - sudo apt-get install cmake
script:

    - mkdir build
    - cd build
    - cmake ..
    - make
